[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dpexample"
version = "1.0.0"
description = "Differential Privacy in Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.19.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "tensorboard>=2.14.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "dpexample.server_app:app"
clientapp = "dpexample.client_app:app"


[tool.flwr.app.config]
num-server-rounds = 50
fraction-evaluate = 0
local-epochs = 1
learning-rate = 0.05
batch-size = 128
max-weight = 9000

# Parameters for the Differential Privacy protocol
noise-multiplier = 0.00000001
clipping-norm = 1000.0
num-partitions = 5

# TensorBoard configuration
tensorboard-run-name = "dp_10clients_local_sim"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-superlink]
options.num-supernodes = 5
address="127.0.0.1:9093"
insecure=true

[tool.flwr.federations.local-simulation]
options.num-supernodes = 5
options.backend.client-resources.num-cpus = 1
options.backend.client-resources.num-gpus = 0
