#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default values
PROJECT_NAME="hereditary_workshop"
SERVER_IP="server1"
FL_PORT=8002
ADMIN_PORT=8003
ADMIN_EMAIL="surf@hereditary.com"
ORG="nvidia"
OUTPUT_YML="${ROOT}/project.yml"

# Default sites array
SITES=("site-1" "site-2" "site-3")

# Parse command line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --name) PROJECT_NAME="$2"; shift ;;
        --server) SERVER_IP="$2"; shift ;;
        --fl-port) FL_PORT="$2"; shift ;;
        --admin-port) ADMIN_PORT="$2"; shift ;;
        --admin) ADMIN_EMAIL="$2"; shift ;;
        --org) ORG="$2"; shift ;;
        --output) OUTPUT_YML="$2"; shift ;;
        --sites)
            shift
            SITES=()
            while [[ "$#" -gt 0 ]] && [[ ! "$1" == --* ]]; do
                SITES+=("$1")
                shift
            done
            # Don't shift again — the next token is already the next flag or end
            continue
            ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

echo "======================================================"
echo "1. Generating Network Topology (${OUTPUT_YML})"
echo "======================================================"
cat > "${OUTPUT_YML}" <<EOF
api_version: 3
name: ${PROJECT_NAME}
description: ${PROJECT_NAME} — Flower + NVIDIA FLARE

participants:
  - name: ${SERVER_IP}
    type: server
    org: ${ORG}
    fed_learn_port: ${FL_PORT}
    admin_port: ${ADMIN_PORT}
EOF

for site in "${SITES[@]}"; do
cat >> "${OUTPUT_YML}" <<EOF
  - name: ${site}
    type: client
    org: ${ORG}
EOF
done

cat >> "${OUTPUT_YML}" <<EOF
  - name: ${ADMIN_EMAIL}
    type: admin
    org: ${ORG}
    role: project_admin

builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file:
        - master_template.yml
        - aws_template.yml
        - azure_template.yml
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      config_folder: config
      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        overseer_exists: false
        args:
          sp_end_point: ${SERVER_IP}:${FL_PORT}:${ADMIN_PORT}
  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder
EOF
echo "Configuration created with server: ${SERVER_IP} and ${#SITES[@]} sites."


echo ""
echo "======================================================"
echo "2. Provisioning Cryptographic Certificates & Workspaces"
echo "======================================================"
PROVISION_W="${ROOT}/nvflare_workspace/provision"
PROD_00="${PROVISION_W}/${PROJECT_NAME}/prod_00"
JOB_EXPORT="${ROOT}/nvflare_workspace/jobs"

mkdir -p "${PROVISION_W}" "${JOB_EXPORT}"

# Clean up existing provision to ensure it always generates fresh ones
rm -rf "${PROVISION_W}/${PROJECT_NAME}"

uv run nvflare provision -w "${PROVISION_W}" -p "${OUTPUT_YML}"

echo "Injecting custom security components into client workspaces..."
for node_name in "${SITES[@]}"; do
    mkdir -p "${PROD_00}/${node_name}/local"
    cp -r "${ROOT}/custom4client/"* "${PROD_00}/${node_name}/local/"
done

echo ""
echo "======================================================"
echo "3. Building Flower NVFlare Job"
echo "======================================================"
echo "  - Packaging cifar10_flower..."
uv run python "${ROOT}/job.py" --export-dir "${JOB_EXPORT}"


echo ""
echo "======================================================"
echo "4. Generating docker-compose.yml"
echo "======================================================"
DOCKER_COMPOSE="${ROOT}/docker-compose.yml"

# Write header and shared service template
cat > "${DOCKER_COMPOSE}" <<EOF
# Auto-generated by build_distribution.sh — do not edit manually.

x-nvflare-service: &nvflare-service
  build:
    context: .
    dockerfile: Dockerfile.nvflare
  networks:
    - nvflare

networks:
  nvflare:
    name: nvflare-${PROJECT_NAME}

services:
  ${SERVER_IP}:
    <<: *nvflare-service
    container_name: ${SERVER_IP}
    hostname: ${SERVER_IP}
    volumes:
      - ${PROD_00}/${SERVER_IP}:/workspace
    working_dir: /workspace/startup
    command: ["./sub_start.sh"]
    ports:
      - "${FL_PORT}:${FL_PORT}"
      - "${ADMIN_PORT}:${ADMIN_PORT}"
EOF

# Add a service block for each client site
for site in "${SITES[@]}"; do
cat >> "${DOCKER_COMPOSE}" <<EOF

  ${site}:
    <<: *nvflare-service
    container_name: ${site}
    hostname: ${site}
    volumes:
      - ${PROD_00}/${site}:/workspace
    working_dir: /workspace/startup
    command: ["./sub_start.sh"]
    depends_on:
      - ${SERVER_IP}
EOF
done

echo "docker-compose.yml generated with server '${SERVER_IP}' and sites: ${SITES[*]}"


echo ""
echo "======================================================"
echo "5. Packaging for Distribution"
echo "======================================================"
DIST_DIR="${ROOT}/dist"
rm -rf "${DIST_DIR}"
mkdir -p "${DIST_DIR}"

for node in "${PROD_00}"/*; do
    if [ -d "${node}" ]; then
        node_name=$(basename "${node}")
        echo "  Packaging ${node_name}..."
        (cd "${PROD_00}" && zip -qr "${DIST_DIR}/${node_name}.zip" "${node_name}")
    fi
done

cp "${ROOT}/Dockerfile.nvflare" "${DIST_DIR}/"
cp "${ROOT}/pyproject.toml" "${DIST_DIR}/"
cp "${ROOT}/uv.lock" "${DIST_DIR}/"


echo ""
echo "Done! All distribution files are in the 'dist' folder:"
ls -lh "${DIST_DIR}"
echo ""
echo "To run locally: docker compose up --build -d"
